// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_jRsQwBaahYxphIh09gX7NkHSa1Yah8Y',
    appId: '1:312112470504:web:802dc2e537fffc3e312c5d',
    messagingSenderId: '312112470504',
    projectId: 'componentes-5d5d3',
    authDomain: 'componentes-5d5d3.firebaseapp.com',
    storageBucket: 'componentes-5d5d3.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQJQ6NVviw74edaZHZgirSzkF-jPpTGqA',
    appId: '1:312112470504:android:1eef0b796718726f312c5d',
    messagingSenderId: '312112470504',
    projectId: 'componentes-5d5d3',
    storageBucket: 'componentes-5d5d3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDwpicvmSyoVMbkzn4zaMijh_j6pnE-VIg',
    appId: '1:312112470504:ios:aa9618ad740b97a5312c5d',
    messagingSenderId: '312112470504',
    projectId: 'componentes-5d5d3',
    storageBucket: 'componentes-5d5d3.appspot.com',
    iosBundleId: 'com.example.practica35b',
  );
}
